### ISSUE TITLE
not an issue. but what is your ui?

### ISSUE THREAD

**Issue by himfan95** [Faydz/PremadeRegionsEU#1]
im just curious what are you using for your ui to make your group finder look like that?

**Comment by Faydz** [comment]
ElvUI
A USER INTERFACE DESIGNED AROUND USER-FRIENDLINESS WITH EXTRA FEATURES THAT ARE NOT INCLUDED IN THE STANDARD UI.

https://www.tukui.org/download.php?ui=elvui
